pipeline {
    agent any

    stages {
        stage('Pull Apache Image') {
            steps {
                script {
                    // Puxa a imagem do Apache
                    sh 'docker pull httpd:latest'
                }
            }
        }

        stage('Run Apache Container') {
            steps {
                script {
                    // Para garantir que o container não esteja rodando, removemos qualquer instância anterior
                    sh 'docker stop apache-server || true'
                    sh 'docker rm apache-server || true'
                    
                    // Inicia o novo container do Apache em primeiro plano
                    sh 'docker run -d --name apache-server -p 3212:80 httpd:latest'
                }
            }
        }
    }

    post {
        always {
            // Exibe os logs do container após a execução
            sh 'docker logs apache-server || true'
        }
    }
}
