pipeline {
    agent any

    stages {
        stage('Run ses-app using Docker Compose') {
            steps {
                script {
                    // Navega até o diretório atualizado
                    sh 'cd /opt/teste-saude'

                    // Executa o Docker Compose para subir o container
                    sh 'docker-compose up -d'
                }
            }
        }
    }

    post {
        always {
            // Exibe os containers em execução
            sh 'docker ps'
        }
    }
}
