pipeline {
    agent any

    stages {
        stage('Docker Build') {
            steps {
                // Criar e rodar o container Apache
                sh 'docker run -d -p 3212:80 --name apache-server httpd'
            }
        }

        stage('Verify') {
            steps {
                // Verifica se o container está rodando
                sh 'docker ps'
            }
        }

        stage('Clean Up') {
            steps {
                // Para e remove o container após o teste
                sh 'docker stop apache-server || true'
                sh 'docker rm apache-server || true'
            }
        }
    }
}
